[project]
drom-version = "0.9.2~dev2"
share-repo = "https://github.com/OCamlPro/drom-share"
share-version = "0.9.2"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@ocamlpro.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro SAS"
edition = "4.13.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.07.0"
name = "header-check"
skeleton = "mini_prg"
synopsis = "A tool to check and update source headers, using checksums"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
The header-check tool scans a source project, lists all existing headers and
can be used to update them. It uses checksums to create identifiers for 
headers and works with OCaml, C/C++ and Shell kinds of comments.
"""

[project]
skip = ["@test", "@sphinx", "docs", "@docs", "@ocamlformat", "@ocp-indent"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
# examples:
#  docker-alpine-image = "ocamlpro/ocaml:4.13"
#  dune-lang = "2.1"
#  readme-trailer = "..."
#  dot-gitignore-trailer = "..."
[fields]
# ...

[[package]]
dir = "src/header-check"
# edit 'src/header-check/package.toml' for package-specific options

